### ISSUE TITLE
Log progress

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fqgrep#2]

**Comment by sstadick** [comment]
`indicatif` just came out with a release that might actually make it usable for this now: https://github.com/console-rs/indicatif/releases/tag/0.17.0.

Using an atomic int was "the idea" mentioned above stolen from how tangram (whose repos seem to now be private) was doing progress logging. Indicatif now uses an atomic int instead of a mutex.

**Comment by nh13** [comment]
@sstadick I see two paths forward:

1. Just log based on # of records read.  This does not give any indication of when it will be done, unless you know the # of records ahead of time.
2. Get the length of each input file (https://doc.rust-lang.org/std/fs/struct.File.html#method.metadata), and as long as they're a regular file (i.e. not piped in), you can get the length of the file (`fh.metadata().unwrap().len()`).  You could then have way to know how many bytes have been read in, etc.  This seems complicated when (1) would suffice.

The `indicatif` is nice for a progress _bar_, but that becomes ugly when written to a log, versus a progress _logger_.  Thoughts?

**Comment by sstadick** [comment]
Yep! You are totally right, a logger makes way more sense than a progress bar.
https://github.com/fulcrumgenomics/fqgrep/pull/10
